######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 30 11:01:31 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cannonfield.h gameboard.h lcdrange.h
SOURCES += cannonfield.cpp gameboard.cpp lcdrange.cpp main.cpp
